####################
# hugo
####################
baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"
title = "myLightning.Network"
summaryLength = 10
RelativeURLs = false
CanonifyURLs = true
enableRobotsTXT = true
enableEmoji = true
paginate = 10
enableGitInfo = true
pygmentsCodefences = true
pygmentsUseClasses = true
disableHugoGeneratorInject = true
assetDir = "static/assets"

[module]
[module.hugoVersion]
extended = true
min = "0.101.0"
timeout = "300s"
disableKinds = ["section"]

# disqus
disqusShortname = 'yourDisqusShortname'

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark.renderer]
    hardWraps = true
    unsafe    = true
    xhtml     = true

[taxonomies]
  category = 'category'
  tag = 'tags'

[outputs]
  home          = ["html", "json"]
  section          = ["html"]

####################
# site params
####################
[params]
  author = "John Doe"
  author_pic = "/assets/images/avatar1.jpg"
  author_bio = "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
  site_name = "myLightning.Network"
  description = "website description"
  motto = "Reporting & Educating about Lightning Network"
  locale = "en-US"
  type = "website"
  favicon = "favicon.png"

  contact_url = "mailto:webmaster@website.com"
  github = "https://github.com/mylightningnetwork"
  twitter = "https://twitter.com/MylightningN"
  youtube = "https://www.youtube.com/channel/UCdUIwB5dz3bSXujpT54jA6w"

####################
# navbar menu
####################
# url can be absolute URL: https://lnfreemarkets.com
# or relative path: /about

[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "News"
url = "/"
weight = 2

[[menu.main]]
name = "Capital Markets"
url = "/magazine"
weight = 3

[[menu.main]]
name = "Game Theory"
url = "/gametheory"
weight = 4
